version: '3.1'
services:
  db:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 6040
    ports:
      - "3306:3306"
    volumes:
      - sistema-de-arquivos-data:/var/lib/mysql

volumes:
  sistema-de-arquivos-data: